version: "3.9"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql2022
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_PASS}
      - MSSQL_PID=Developer # Bisa diganti: Developer | Express | Standard | Enterprise
      - MSSQL_COLLATION=SQL_Latin1_General_CP1_CI_AS
    ports:
      - "14332:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets
      - ./temp_bu:/var/opt/mssql/temp_bu

volumes:
  data:
  log:
  secrets:
